#include "audio_definition.h"
#ifndef USER_AUDIO_CONFIG_FOR_LIB_H_
#define USER_AUDIO_CONFIG_FOR_LIB_H_

#define USER_AUDIO_OUTPUT_MODE AUDIO_OUTPUT_MODE_DIFFERENTIAL
#define USER_AUDIO_SAMPLERATE AUDIO_SAMPLERATE_8K
#define USER_AUDIO_RESOLUTION AUDIO_RESOLUTION_8BIT
#define USER_AUDIO_PCM_FORMAT AUDIO_PCM_UNSIGNED
#define AUDIO_PCM_VOLUME_CONFIG AUDIO_PCM_VOLUME_1_2

#define RESOLUTION_DEFAULT 8
_Static_assert(RESOLUTION_DEFAULT <= USER_AUDIO_RESOLUTION*8, "The resolution is not supported!!!");
#endif
